### ISSUE TITLE
Refactor introduced error

### ISSUE THREAD

**Issue by AI-Casanova** [elias-gaeros/resize_lora#2]
```
SVD:   0% 1/986 [00:00<03:33,  4.61it/s]WARNING:root:LoRA layer lora_te1_text_model_encoder_layers_11_mlp_fc1 is all zeroes! dim=32
WARNING:root:LoRA layer lora_te1_text_model_encoder_layers_11_mlp_fc2 is all zeroes! dim=32
WARNING:root:LoRA layer lora_te1_text_model_encoder_layers_11_self_attn_k_proj is all zeroes! dim=32
WARNING:root:LoRA layer lora_te1_text_model_encoder_layers_11_self_attn_out_proj is all zeroes! dim=32
WARNING:root:LoRA layer lora_te1_text_model_encoder_layers_11_self_attn_q_proj is all zeroes! dim=32
WARNING:root:LoRA layer lora_te1_text_model_encoder_layers_11_self_attn_v_proj is all zeroes! dim=32
SVD: 100% 986/986 [00:04<00:00, 233.43it/s]
Scoring spn_ckpt=1,thr=-1.2,rescale=0.2: 100% 980/980 [00:00<00:00, 4213.92it/s]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/resize_lora/resize_lora.py", line 302, in <module>
    main()
  File "/content/gdrive/MyDrive/resize_lora/resize_lora.py", line 290, in main
    process_lora_model(
  File "/content/gdrive/MyDrive/resize_lora/resize_lora.py", line 198, in process_lora_model
    sd, threshold = recipe.resize_lora(
  File "/content/gdrive/MyDrive/resize_lora/resize_lora.py", line 140, in resize_lora
    mask = layer_scores > threshold
UnboundLocalError: local variable 'threshold' referenced before assignment
```

**Comment by elias-gaeros** [comment]
Woops. I guess I didn't test with `thr=x`. Fixed, thanks for reporting.

**Comment by AI-Casanova** [comment]
Of course! I like what you've created.
